
sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]
      

sonata_admin:
  title: 'SantiagueñoBus'
  title_logo: images/apple-touch-icon.png

  show_mosaic_button:   false

  security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

  dashboard:
    blocks:
        -
            position: left
            type: sonata.admin.block.admin_list
            settings:
                groups: [gservicio, gtransporte, glocalizacion, gusuarios, fug_servicios]
            roles: [ROLE_USER]
        # -
        #     position: left
        #     type: sonata.admin.block.admin_list
        #     settings:
        #         groups: [fug_servicios]
        #     roles: [ ROLE_FINAL_USER ]
    groups:
        gservicio:
            label: Servicios
            items:
                - admin.servicio
                - admin.reserva
                - admin.boleto
                - admin.pago
                - admin.pasajero
            roles: [ROLE_OPERATOR, ROLE_FINAL_USER]
        gtransporte:
            label: Transporte
            items:
                - admin.transporte
                - admin.vehiculo
                - admin.marca
                - admin.modelo
                # - admin.transporte_asiento
        glocalizacion:
            label: Localización
            items:
                - admin.provincia
                - admin.ciudad
                - admin.trayecto
                - admin.trayecto_parada
                - admin.parada
        gusuarios:
            label: Usuarios y permisos
            items:
                - sonata.user.admin.user
        fug_servicios:
            label: Usuario
            items:
                - label: 'Mis Boletos' # Texto que se mostrará en el enlace
                  route: 'app_misboletos' # El nombre de la ruta de tu controlador
                  # route_parameters: { param1: value1 } # Si tu ruta requiere parámetros
                  # icon: 'fa fa-ticket-alt' # Opcional: un icono para el enlace
                  # roles: [ROLE_ADMIN] # Opcional: Restringe quién ve este enlace
            roles: [ROLE_FINAL_USER]

