App\Entity\Marca:
    properties:
        descripcion:
            - NotBlank: ~

App\Entity\Boleto:
#    constraints:
#        - App\Validator\ConfirmedPaymentReceipt: ~
    properties:
        costo:
            - GreaterThan: 500

App\Entity\Servicio:
    constraints:
        - Sonata\Form\Validator\Constraints\InlineConstraint:
            service: app.inlinevalidator.servicio
            method: validate

App\Entity\Reserva:
    constraints:
        - Sonata\Form\Validator\Constraints\InlineConstraint:
            service: app.inlinevalidator.reserva
            method: validate

App\Entity\Trayecto:
    constraints:
        - Sonata\Form\Validator\Constraints\InlineConstraint:
            service: app.inlinevalidator.trayecto
            method: validate

App\Entity\ConfigPrecio:
    constraints:
        - Sonata\Form\Validator\Constraints\InlineConstraint:
            service: app.inlinevalidator.config_precio
            method: validate

App\Form\Model\Registro:
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 3
                max: 64
        apellido:
            - NotBlank: ~
            - Length:
                min: 3
                max: 64
        nro_documento:
            - Range:
                min: 1000000
                max: 100000000
                notInRangeMessage: "DNI no válido."
