# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'es'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # admin.colectivo:
    #     class: App\Admin\ColectivoAdmin
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\Colectivo, controller: App\Controller\ColectivoAdminController, manager_type: orm, group: admin, label: Colectivo }
    #     calls:
    #       - [addChild, ['@admin.asiento', 'colectivo']]

    admin.modelo:
        class: App\Admin\ModeloAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Modelo, controller: App\Controller\ModeloAdminController, manager_type: orm, group: admin, label: Modelo }

    admin.marca:
        class: App\Admin\MarcaAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Marca, controller: App\Controller\MarcaAdminController, manager_type: orm, group: admin, label: Marca }

    # admin.asiento_colectivo:
    #     class: App\Admin\AsientoColectivoAdmin
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\AsientoColectivo, controller: App\Controller\AsientoColectivoAdminController, manager_type: orm, group: admin, label: AsientoColectivo }
    #
    # admin.asiento:
    #     class: App\Admin\AsientoAdmin
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\Asiento, controller: App\Controller\AsientoAdminController, manager_type: orm, group: admin, label: Asiento }

    # admin.pasaje:
    #     class: App\Admin\PasajeAdmin
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\Pasaje, controller: App\Controller\PasajeAdminController, manager_type: orm, group: admin, label: Pasaje }

    # admin.viaje:
    #     class: App\Admin\ViajeAdmin
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\Viaje, controller: App\Controller\ViajeAdminController, manager_type: orm, group: admin, label: Viaje }
    #     calls:
    #         - [ addChild, [ "@admin.pasaje", 'viaje' ] ]

    admin.pago:
        class: App\Admin\PagoAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Pago, controller: App\Controller\PagoAdminController, manager_type: orm, group: admin, label: Pago }
        calls:
            - [ addChild, [ "@admin.pasaje" ] ]

    admin.pasajero:
        class: App\Admin\PasajeroAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Pasajero, controller: App\Controller\PasajeroAdminController, manager_type: orm, group: admin, label: Pasajero }
